### ISSUE TITLE
2.30.0 is unavailable on Gradle repository

### ISSUE THREAD

**Issue by njimenezotto** [diffplug/spotless#1319]
Gradle plugin com.diffplug.gradle.spotless:com.diffplug.gradle.spotless.gradle.plugin:6.11.0 is failing on build because of spotless-lib:2.30.0 and spotless-lib-extra:2.30.0.
They are not available.

https://search.maven.org/artifact/com.diffplug.spotless/spotless-lib
https://search.maven.org/artifact/com.diffplug.spotless/spotless-lib-extra

But v2.30.0 appears on https://github.com/diffplug/spotless/blob/main/CHANGES.md

`
> Could not resolve all files for configuration ':classpath'.
   > Could not find com.diffplug.spotless:spotless-lib:2.30.0.
     Searched in the following locations:
       - file:/Users/njimenez/.m2/repository/com/diffplug/spotless/spotless-lib/2.30.0/spotless-lib-2.30.0.pom
       - https://repo.maven.apache.org/maven2/com/diffplug/spotless/spotless-lib/2.30.0/spotless-lib-2.30.0.pom
       - https://plugins.gradle.org/m2/com/diffplug/spotless/spotless-lib/2.30.0/spotless-lib-2.30.0.pom
     Required by:
         project : > com.diffplug.gradle.spotless:com.diffplug.gradle.spotless.gradle.plugin:6.11.0 > com.diffplug.spotless:spotless-plugin-gradle:6.11.0
   > Could not find com.diffplug.spotless:spotless-lib-extra:2.30.0.
     Searched in the following locations:
       - file:/Users/njimenez/.m2/repository/com/diffplug/spotless/spotless-lib-extra/2.30.0/spotless-lib-extra-2.30.0.pom
       - https://repo.maven.apache.org/maven2/com/diffplug/spotless/spotless-lib-extra/2.30.0/spotless-lib-extra-2.30.0.pom
       - https://plugins.gradle.org/m2/com/diffplug/spotless/spotless-lib-extra/2.30.0/spotless-lib-extra-2.30.0.pom
     Required by:
         project : > com.diffplug.gradle.spotless:com.diffplug.gradle.spotless.gradle.plugin:6.11.0 > com.diffplug.spotless:spotless-plugin-gradle:6.11.0

`

**Comment by jvanderwee** [comment]
Looks like the CircleCI job which deploys the artifacts is still running https://github.com/diffplug/spotless/runs/8343619081

**Comment by nedtwigg** [comment]
Very strange... The CI job which deployed this most recent (failed) publish of `2.30.0` is here:

https://app.circleci.com/pipelines/github/diffplug/spotless/2355/workflows/38b72e7d-252a-4b06-bfc7-e979f1e8c352/jobs/13274

The previous successful publish of `2.29.0` is here:

https://app.circleci.com/pipelines/github/diffplug/spotless/2203/workflows/9e71288e-c99d-4da1-87f9-edbd49e27887/jobs/12484

The Gradle plugin portal publish succeeded, but none of the maven central publishes actually happened (not lib, lib-extra, nor the maven plugin). The console log indicates that it worked, and I got emails from Sonatype Lift that indicated that at least parts of the deploy pipeline happened.

When I diff the two console logs, everything related to the publish is the same

```diff
<   UP_TO_DATE (null)...cec88e2037daa772d1720d080762113dc69b2327
---
>   UP_TO_DATE (null)...aadeaef0861309b8a4aadd5c04c8436451cdd82f
28a18,38
> > Task :lib:compileCompatKtLintApiJava
> > Task :lib:processCompatKtLintApiResources NO-SOURCE
> > Task :lib:compatKtLintApiClasses
> > Task :lib:compileCompatKtLint0Dot31Dot0Java
> > Task :lib:processCompatKtLint0Dot31Dot0Resources NO-SOURCE
> > Task :lib:compatKtLint0Dot31Dot0Classes
> > Task :lib:compileCompatKtLint0Dot32Dot0Java
> > Task :lib:processCompatKtLint0Dot32Dot0Resources NO-SOURCE
> > Task :lib:compatKtLint0Dot32Dot0Classes
> > Task :lib:compileCompatKtLint0Dot34Dot2Java
> > Task :lib:processCompatKtLint0Dot34Dot2Resources NO-SOURCE
> > Task :lib:compatKtLint0Dot34Dot2Classes
> > Task :lib:compileCompatKtLint0Dot45Dot2Java
> > Task :lib:processCompatKtLint0Dot45Dot2Resources NO-SOURCE
> > Task :lib:compatKtLint0Dot45Dot2Classes
> > Task :lib:compileCompatKtLint0Dot46Dot0Java
> > Task :lib:processCompatKtLint0Dot46Dot0Resources NO-SOURCE
> > Task :lib:compatKtLint0Dot46Dot0Classes
> > Task :lib:compileCompatKtLint0Dot47Dot0Java
> > Task :lib:processCompatKtLint0Dot47Dot0Resources NO-SOURCE
> > Task :lib:compatKtLint0Dot47Dot0Classes
69c79
< Created staging repository 'comdiffplug-1080' at https://s01.oss.sonatype.org/service/local/repositories/comdiffplug-1080/content/
---
> Created staging repository 'comdiffplug-1083' at https://s01.oss.sonatype.org/service/local/repositories/comdiffplug-1083/content/
87,88c97,98
< push refs/tags/lib/2.29.0 to origin git@github.com:diffplug/spotless.git
<   OK 0000000000000000000000000000000000000000...a85788c79b8ede73d077736de7065023e62d8ba4 fastForward
---
> push refs/tags/lib/2.30.0 to origin git@github.com:diffplug/spotless.git
>   OK 0000000000000000000000000000000000000000...626d44f723bc371383052450012fe01ab72cc1dc fastForward
90c100
<   OK cec88e2037daa772d1720d080762113dc69b2327...1dfd0ee20868f9ca1b76817ae143712b3df8d729 fastForward
---
>   OK aadeaef0861309b8a4aadd5c04c8436451cdd82f...6cee33d6f035b462be5800c154d86ecad63cdd57 fastForward
92,93c102,103
< BUILD SUCCESSFUL in 1m 25s
< 38 actionable tasks: 38 executed
\ No newline at end of file
---
> BUILD SUCCESSFUL in 2m 26s
> 45 actionable tasks: 45 executed
\ No newline at end of file
```

If you [compare the codebase at `lib/2.29.0` vs `lib/2.30.0`](https://github.com/diffplug/spotless/compare/lib/2.29.0...lib/2.30.0) the only differences related to the build that I can see are:

- bump Gradle from `7.5` -> `7.5.1`
- bump Gradle plugin `com.github.spotbugs 5.0.10 -> 5.0.12`
- bump Gradle plugin `org.gradle.test-retry 1.4.0 -> 1.4.1`
- add Gradle plugin `io.github.davidburstrom.version-compatibility` plugin to the `lib` build (shouldn't matter)

I logged into `s01.oss.sonatype.org`, and I don't have any staging repositories there:

<img width="450" alt="image" src="https://user-images.githubusercontent.com/2924992/190223816-65d722d5-2db2-49e4-be1f-3ed7409ed064.png">

But the collective staging repositories

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/2924992/190224867-d3eebf85-cf34-483e-b6d3-6f9c69fa5149.png">

And collective release repositories

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/2924992/190225129-10bd84f4-7cad-4ae4-91fa-48ad030ecd39.png">

And the "Public repositories" all have it 

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/2924992/190225315-d2244125-1794-4390-ac37-11655f6d752f.png">

So I think the problem is some kind of sync from `s01.oss.sonatype.org` to mavencentral.  I'm continuing to investigate...

**Comment by nedtwigg** [comment]
Yeah, I'm pretty sure this was just a slow sync from `s01` to `repo1` on the Sonatype side. `2.30` isn't showing up in search, but it's clearly there. In the stacktrace at the top

```
Could not find com.diffplug.spotless:spotless-lib:2.30.0.
Searched in the following locations:
- file:/Users/njimenez/.m2/repository/com/diffplug/spotless/spotless-lib/2.30.0/spotless-lib-2.30.0.pom
- https://repo.maven.apache.org/maven2/com/diffplug/spotless/spotless-lib/2.30.0/spotless-lib-2.30.0.pom
- https://plugins.gradle.org/m2/com/diffplug/spotless/spotless-lib/2.30.0/spotless-lib-2.30.0.pom
```

The pom link https://repo.maven.apache.org/maven2/com/diffplug/spotless/spotless-lib/2.30.0/spotless-lib-2.30.0.pom is now clearly working. No action taken on my part, just a slow sync. Frowny face. I'm gonna email Sonatype to ask what the expected sync time is supposed to be.

This should be resolved now, if it isn't, please post back and I'll reopen.

**Comment by njimenezotto** [comment]
Thanks a lot for your analyse. It's working.

**Comment by deeptechs** [comment]
We are still not able to download in our CI/CD environments. You can check the browser pages. There is only pom file..
Also this deployment is still running.. https://github.com/diffplug/spotless/runs/8343619081

![image](https://user-images.githubusercontent.com/29144075/198965547-afabd288-a867-45f3-b82d-5d81ecad1982.png)

![image](https://user-images.githubusercontent.com/29144075/198966023-14320bbc-d7b5-429d-8560-729c4e359322.png)
